version : "3.3"
services :
  web :
     build : .
     ports :
         - "8000:8000"
     volumes:
      - ./:/data 
      - ./volume/store_data/db.sqlite3:/data/db.sqlite3
     restart: unless-stopped
     environment:
      - PYTHONUNBUFFERED=1  # Real-time logs
      - DJANGO_DEBUG=1      # Enable Django debug mode
      - WATCHFILES_FORCE_POLLING=1
      - DJANGO_TEMPLATE_DEBUG=1  # 👈 New environment variable
     command: >
       sh -c "python manage.py migrate && 
       python manage.py runserver 0.0.0.0:8000"
